### ISSUE TITLE
WebHooks

### ISSUE THREAD

**Issue by DaTebe** [evermax/dockerfiles#2]
Hi,

I'm trying to use webhooks with your docker ADL LRS. But it my webhooks won't be saved.
Also in the admin menu of the webhooks a input field is missing ('endpoint').
I've checked the log files, but they where empty.

Do you have any idea about this? Maybe missing files? 

Greetings Daniel

**Comment by evermax** [comment]
Hi!
That is curious. Is it there on the non dockerized version?

I will look into it when I get back home, there might be some parameters that needs to be changed in the config file or something like that.

If it is indeed a configuration problem, I will probably add an env variable for it, so that people can choose to have webhooks or not.

**Comment by DaTebe** [comment]
Hi, thanks for your reply!
I've set `USE_HOOKS = True` in the `settings.py`. Also I rebuild the image and the container. For me it is strange, that there is something missing in the GUI. Maybe this is also a bug in the original ADL LRS? I don't know which version I downloaded. but it's a few days old.

EDIT:
That is really strange. ADL LRS does not like my endpoint. If I type `http://localhost:8080` everything is fine. If I type `http://logstash:5001` the hook will not be saved. I'll test this on my ADL LRS which is installed on my host. If it behaves the same I'll open an issue at adlnet/ADL_LRS

EDIT2: It seems to be a problem with ADL LRS in general

**Comment by evermax** [comment]
Ok, if you confirm that the issue is on the LRS before I can have a look at it, let me know.

**Comment by DaTebe** [comment]
I've posted n issue at the ADL LRS repo. I think it's definitely a ADL LRS story.

**Comment by DaTebe** [comment]
Hello,

Maybe you can help me with another problem. It seems that the dockerized ADL LRS does not send any WebHooks. I've made a bin at [RequestBin](http://requestb.in/) but I don't receive any data on it. 

Is Celery working in the docker container? I also don't get any logging information in the celery_tasks.log

EDIT: I've did a little bit of logging. It seems that the celery function delay() will not be called. I searched a little bit. In the `celery.py` the `RABBITMQ_URL` does not contain a `vhost` at the end. Is this normal?

EDIT2: I've removed the delay function and it now sends webhooks without any problem. I can live with this solution. But maybe you have an idea how to solve this the right way?

**Comment by evermax** [comment]
I don't think the RabbitMQ url needs a vhost but I might to play with that and also see what the errors are.
I'll look it up later today, I think I remember having a similar issue though. So hopefully I'll figure something out!

EDIT: I couldn't find something, there is indeed no logs. I will dig more into that tomorrow. I don't really understand why there is no connection to the RabbitMQ instance.
