### ISSUE TITLE
fabric.api 2.0 is not compatible

### ISSUE THREAD

**Issue by riolcrt** [evermax/dockerfiles#3]
Build the Docker Image fails with error:

```
File "/workspace/ADL_LRS/fabfile.py", line 3, in <module>
    from fabric.api import local
ImportError: No module named api
```
The problem is in the docker file line 5. 

`RUN pip install --upgrade pip; pip install fabric`

It installs fabric > 2.0 wich is not compatible with adl_lrs.

It have to specify the version. Something like:

`RUN pip install --upgrade pip; pip install 'fabric<2.0'`

**Comment by evermax** [comment]
Thanks for pointing this out!
I will look at it tonight and update the Dockerfile.

Feel free to submit a PR too if you get it to work before that.
